spring.application.name=DocAlert

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Server Configuration
server.error.include-message=always
server.error.include-binding-errors=always
server.port=${PORT:8080}

# PostgreSQL Database Configuration (Railway)
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL Database Configuration (Local)
# spring.datasource.url=jdbc:postgresql://localhost:5432/railway_local
# spring.datasource.username=postgres
# spring.datasource.password=soni123
# spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Configuration
spring.jpa.properties.hibernate.connection.characterEncoding=utf8
spring.jpa.properties.hibernate.connection.CharSet=utf8
spring.jpa.properties.hibernate.connection.useUnicode=true

# Email Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c002c8de41339d
spring.mail.password=8de184449f9c95
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply@obnovime.com

# Application Email Settings
app.notification.email=farike7341@btcours.com

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# SQL Initialization - Only Schema, No Data // set mode=always to create schema
spring.sql.init.mode=never
spring.sql.init.platform=postgresql
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=false
spring.sql.init.continue-on-error=false

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE