-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS document_files;
DROP TABLE IF EXISTS responsible_person;
DROP TABLE IF EXISTS vehicle_inspection_periods;
DROP TABLE IF EXISTS document_types;
DROP TABLE IF EXISTS document_statuses;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS resource_types;
DROP TABLE IF EXISTS app_user;

-- Create tables in order of dependencies

-- Users and Roles
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT DEFAULT 'N/A',
    password TEXT DEFAULT '',
    user_type TEXT DEFAULT 'N/A',
    first_name TEXT DEFAULT 'N/A',
    last_name TEXT DEFAULT 'N/A',
    phone_number TEXT DEFAULT 'N/A',
    address TEXT DEFAULT 'N/A'
);

-- Document Management Tables
CREATE TABLE document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'N/A'
);

CREATE TABLE document_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'N/A'
);

CREATE TABLE vehicle_inspection_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT DEFAULT 'N/A',
    days_until_renewal INTEGER
);

-- Resource Management Tables
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'N/A'
);

CREATE TABLE resource_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'N/A'
);

-- Responsible Person Table
CREATE TABLE responsible_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position TEXT DEFAULT 'N/A',
    department TEXT DEFAULT 'N/A',
    app_user_id BIGINT REFERENCES app_user(id)
);

-- Main Document Table
CREATE TABLE document_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'N/A',
    number TEXT DEFAULT 'N/A',
    renewal_date DATE,
    renewal_period INTEGER,
    service_provider TEXT DEFAULT 'N/A',
    arhiva BOOLEAN,
    document_type_id BIGINT REFERENCES document_types(id),
    location_id BIGINT REFERENCES locations(id),
    resource_type_id BIGINT REFERENCES resource_types(id),
    responsible_person_id BIGINT REFERENCES responsible_person(id),
    status_id BIGINT REFERENCES document_statuses(id),
    vehicle_inspection_period_id BIGINT REFERENCES vehicle_inspection_periods(id),
    created_by BIGINT REFERENCES app_user(id)
);
