-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS document_files;
DROP TABLE IF EXISTS responsible_person;
DROP TABLE IF EXISTS vehicle_inspection_periods;
DROP TABLE IF EXISTS document_types;
DROP TABLE IF EXISTS document_statuses;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS resource_types;
DROP TABLE IF EXISTS app_user;

-- Create tables in order of dependencies

-- Users and Roles
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT DEFAULT '-',
    password TEXT DEFAULT '',
    user_type TEXT DEFAULT '-',
    department text DEFAULT '-',
    first_name TEXT DEFAULT '-',
    last_name TEXT DEFAULT '-',
    phone_number TEXT DEFAULT '-'
);

-- Document Management Tables
CREATE TABLE document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '-',
    renewal_period INTEGER DEFAULT 0
);

CREATE TABLE document_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '-'
);

-- Resource Management Tables
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '-'
);

CREATE TABLE resource_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '-'
);

-- Main Document Table
CREATE TABLE document_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '-',
    number TEXT DEFAULT '-',
    renewal_date DATE,
    service_provider TEXT DEFAULT '-',
    arhiva BOOLEAN,
    notes TEXT DEFAULT '-',
    document_type_id BIGINT REFERENCES document_types(id),
    location_id BIGINT REFERENCES locations(id),
    resource_type_id BIGINT REFERENCES resource_types(id),
    responsible_person_id BIGINT REFERENCES app_user(id),
    status_id BIGINT REFERENCES document_statuses(id),
    created_by BIGINT REFERENCES app_user(id)
);

CREATE TABLE renewal_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renewed_by_id BIGINT REFERENCES app_user(id),
    doucment_file_id BIGINT REFERENCES document_files(id)
);
